version: '3.9'
services:
  client:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    networks:
      - mentorstudent
    depends_on:
      - server
  server:
    container_name: server
    build: ./server
    ports:
      - 4000:4000
    networks:
      - mentorstudent
    depends_on:
      - db
  db:
    container_name: database
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /db:/data/db
    networks:
      - mentorstudent
networks:
  mentorstudent:
volumes:
  db: